
package com.rit.todolist.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TodoList", targetNamespace = "http://services.todolist.rit.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TodoList {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserId", targetNamespace = "http://services.todolist.rit.com/", className = "com.rit.todolist.services.GetUserId")
    @ResponseWrapper(localName = "getUserIdResponse", targetNamespace = "http://services.todolist.rit.com/", className = "com.rit.todolist.services.GetUserIdResponse")
    @Action(input = "http://services.todolist.rit.com/TodoList/getUserIdRequest", output = "http://services.todolist.rit.com/TodoList/getUserIdResponse")
    public String getUserId(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAuth", targetNamespace = "http://services.todolist.rit.com/", className = "com.rit.todolist.services.GetAuth")
    @ResponseWrapper(localName = "getAuthResponse", targetNamespace = "http://services.todolist.rit.com/", className = "com.rit.todolist.services.GetAuthResponse")
    @Action(input = "http://services.todolist.rit.com/TodoList/getAuthRequest", output = "http://services.todolist.rit.com/TodoList/getAuthResponse")
    public boolean getAuth(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
